apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fake-news

resources:
  - namespace.yaml
  - api-deployment.yaml
  - api-hpa.yaml
  - redis-deployment.yaml
  - networkpolicy.yaml

configMapGenerator:
  - name: fake-news-config
    files:
      - default.yaml=../../configs/default.yaml

commonLabels:
  app.kubernetes.io/name: fake-news-detection
  app.kubernetes.io/part-of: fake-news-detection
  app.kubernetes.io/managed-by: kustomize
