apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fake-news-redis-isolation
  labels:
    app.kubernetes.io/name: fake-news-detection
spec:
  podSelector:
    matchLabels:
      app: fake-news-redis
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: fake-news-api
      ports:
        - protocol: TCP
          port: 6379
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
