apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fake-news-api
  labels:
    app.kubernetes.io/name: fake-news-detection
    release: prometheus
spec:
  selector:
    matchLabels:
      app: fake-news-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
      scheme: http
